apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: fsm-test
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/mongo-data"
